LR: 3.0e-4
NUM_ENVS: 1024
NUM_STEPS: 100
TOTAL_TIMESTEPS: 1.0e7
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 32
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.0
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "tanh"
ENV_NAME: "rodent"
ANNEAL_LR: false
NORMALIZE_ENV: true
DEBUG: true
CHECKPOINT_DIR: "./checkpoints"
